### PR TITLE
Ko dd-5444

### PR DESCRIPTION
**Pull request by Kevinoh47**

### CODE REVIEW

**Comment by Kevinoh47** [comment]
sorry this took so long to create a PR. I have to log into github using kevinoh_ihme to use copilot, and didn't realize that i had to be signed in as my personal github account to open a PR on ihmeuw-scicomp/jobmon.

**Review by mlsandar — CHANGES_REQUESTED** [review]
Can you convert the plain text to something like this quick sample I pulled from chat GPT?
```
from sqlalchemy import create_engine, MetaData, Table, Column, Integer, String, update, literal_column
from sqlalchemy.sql import select

# Define your database URL
engine = create_engine('your_database_url')

# Assuming you have metadata and table definition
metadata = MetaData()
task_instance = Table('task_instance', metadata,
                      Column('id', Integer, primary_key=True),
                      Column('distributor_id', String))

# Sample data for values_clause
values_clause = [
    (1, 'distributor1'),
    (2, 'distributor2'),
    # Add more tuples as needed
]

# Create a CTE (Common Table Expression)
distributor_updates_cte = (
    select(
        [literal_column(str(task_instance_id)).label('task_instance_id'),
         literal_column(f"'{distributor_id}'").label('distributor_id')]
    ).select_from(literal_column('VALUES ' + ', '.join(
        f"({task_instance_id}, '{distributor_id}')" for task_instance_id, distributor_id in values_clause)
    ).alias('distributor_updates_cte'))
).cte('distributor_updates')

# Define the update statement using SQLAlchemy Core
stmt = (
    update(task_instance)
    .values(distributor_id=distributor_updates_cte.c.distributor_id)
    .where(task_instance.c.id == distributor_updates_cte.c.task_instance_id)
)

# Execute the statement
with engine.connect() as connection:
    connection.execute(stmt)
```

**Comment by Kevinoh47** [comment]
@mlsandar so far i have not been able to get any version of the above to pass the unit tests, though I am still working on it.  
May I ask your motivation for the suggested change?

**Comment by Kevinoh47** [comment]
OK @mlsandar I hope this change addresses both the need for sql agnosticism and prevention of sql injection.

**Review by mlsandar — APPROVED** [review]

**Pull request merged**
